#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/outputs"
REPORT="$OUT_DIR/env_check_report.md"
mkdir -p "$OUT_DIR"

if [ -f "$ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$ROOT/.env"
  set +a
fi

status_for_cmd() {
  local name="$1"
  if command -v "$name" >/dev/null 2>&1; then
    printf "found"
  else
    printf "missing"
  fi
}

version_for_cmd() {
  local name="$1"
  shift || true
  if command -v "$name" >/dev/null 2>&1; then
    "$name" "$@" 2>&1 | head -n 1 | tr -d '\r'
  else
    printf "not available"
  fi
}

python_status="missing"
python_version="not available"
if command -v python3 >/dev/null 2>&1; then
  python_status="found"
  python_version="$(python3 --version 2>&1 | head -n 1)"
elif command -v python >/dev/null 2>&1; then
  python_status="found"
  python_version="$(python --version 2>&1 | head -n 1)"
fi

pip_status="missing"
pip_version="not available"
if command -v pip3 >/dev/null 2>&1; then
  pip_status="found"
  pip_version="$(pip3 --version 2>&1 | head -n 1)"
elif command -v pip >/dev/null 2>&1; then
  pip_status="found"
  pip_version="$(pip --version 2>&1 | head -n 1)"
fi

llm_base_url_set=false
llm_model_name_set=false
llm_api_key_set=false
hf_token_set=false
if [ -n "${BASE_URL:-${LLM_BASE_URL:-}}" ]; then llm_base_url_set=true; fi
if [ -n "${MODEL:-${LLM_MODEL_NAME:-}}" ]; then llm_model_name_set=true; fi
if [ -n "${API_KEY:-${LLM_API_KEY:-}}" ]; then llm_api_key_set=true; fi
if [ -n "${HF_TOKEN:-}" ] || [ -n "${HUGGINGFACEHUB_API_TOKEN:-}" ]; then hf_token_set=true; fi

{
  echo "# Environment check report"
  echo
  echo "- Generated by: \`scripts/check_env.sh\`"
  echo "- Scope: local dependency and environment-variable presence check only"
  echo "- Model API called: no"
  echo
  echo "## Tools"
  echo
  echo "| Item | Status | Version / note |"
  echo "| --- | --- | --- |"
  echo "| Python | $python_status | $python_version |"
  echo "| pip | $pip_status | $pip_version |"
  echo "| tshark | $(status_for_cmd tshark) | $(version_for_cmd tshark --version) |"
  echo "| Zeek | $(status_for_cmd zeek) | $(version_for_cmd zeek --version) |"
  echo "| Docker | $(status_for_cmd docker) | optional; $(version_for_cmd docker --version) |"
  echo
  echo "## LLM environment variables"
  echo
  echo "| Variable | Configured | Value printed |"
  echo "| --- | --- | --- |"
  echo "| BASE_URL / LLM_BASE_URL | $llm_base_url_set | no |"
  echo "| MODEL / LLM_MODEL_NAME | $llm_model_name_set | no |"
  echo "| API_KEY / LLM_API_KEY | $llm_api_key_set | no |"
  echo "| HF_TOKEN / HUGGINGFACEHUB_API_TOKEN | $hf_token_set | no |"
  echo
  echo "No OpenAI-compatible, Hugging Face, or other online model endpoint was called."
} > "$REPORT"

echo "wrote $REPORT"
